name = "PMTSimulation"
uuid = "41f40801-0ef4-4c1e-8920-1ad3d0975ff3"
authors = ["Christian Haack"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
